<?xml version="1.0"?>
<package format="3">
  <name>adam_slam</name>
  <version>1.0.0</version>
  <description>Cartographer 2D SLAM wrapper for Robot Adam</description>
  <maintainer email="adam@example.com">Adam Team</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>cartographer_ros</depend>
  <depend>nav_msgs</depend>
  <exec_depend>custom_explorer</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>